#!/usr/bin/env bash
# Generate all the secrets needed by the platform in one shot:
#   - JWT RSA key pair (PEM, 2048-bit)
#   - INTERNAL_API_SECRET (32 bytes, base64url)
#   - GOOGLE_OAUTH_STATE_SECRET (32 bytes, base64url)
#   - POSTGRES_PASSWORD (24 bytes, base64url)
#
# Output: writes a `.env.generated` file in the repo root with all the values.
# Review it, then merge into your real .env / secrets manager.
#
# Usage:
#   ./scripts/generate-keys.sh             # writes .env.generated
#   ./scripts/generate-keys.sh --force     # overwrite if exists
#   ./scripts/generate-keys.sh --stdout    # print to stdout, don't write a file
#
# Re-running with --force gives you a NEW set of secrets — useful for
# rotation. To rotate JWT keys gracefully, see docs/RUNBOOK.md (you keep the
# previous key as JWT_*_KEY_PEM_PREVIOUS during the rotation window).

set -euo pipefail

OUT_FILE=".env.generated"
FORCE=0
TO_STDOUT=0

for arg in "$@"; do
  case "$arg" in
    --force)   FORCE=1 ;;
    --stdout)  TO_STDOUT=1 ;;
    -h|--help)
      sed -n '1,/^set -euo/p' "$0" | head -n 20
      exit 0
      ;;
    *) echo "unknown arg: $arg" >&2; exit 2 ;;
  esac
done

if [ "$TO_STDOUT" -eq 0 ] && [ -f "$OUT_FILE" ] && [ "$FORCE" -eq 0 ]; then
  echo "✗ $OUT_FILE already exists. Pass --force to overwrite." >&2
  exit 1
fi

# Helper: 32-byte base64url-ish secret
gen_secret() {
  openssl rand -base64 "$1" | tr -d '\n=' | tr '+/' '-_'
}

TMPDIR=$(mktemp -d)
trap 'rm -rf "$TMPDIR"' EXIT

openssl genrsa -out "$TMPDIR/jwt_private.pem" 2048 2>/dev/null
openssl rsa -in "$TMPDIR/jwt_private.pem" -pubout -out "$TMPDIR/jwt_public.pem" 2>/dev/null

JWT_PRIV=$(cat "$TMPDIR/jwt_private.pem")
JWT_PUB=$(cat "$TMPDIR/jwt_public.pem")

INTERNAL=$(gen_secret 32)
GOOGLE_STATE=$(gen_secret 32)
PG_PASS=$(gen_secret 24)

emit() {
  cat <<EOF
# Generated by scripts/generate-keys.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Do NOT commit this file — copy values into .env / secrets manager and delete.

POSTGRES_PASSWORD=$PG_PASS
INTERNAL_API_SECRET=$INTERNAL
GOOGLE_OAUTH_STATE_SECRET=$GOOGLE_STATE

# JWT signing key pair (PEM). Both vars must be set in the auth-service env.
# To rotate: move CURRENT to *_PREVIOUS, install new pair, redeploy.
JWT_PRIVATE_KEY_PEM="$JWT_PRIV"
JWT_PUBLIC_KEY_PEM="$JWT_PUB"
EOF
}

if [ "$TO_STDOUT" -eq 1 ]; then
  emit
else
  emit > "$OUT_FILE"
  chmod 600 "$OUT_FILE"
  echo "✓ wrote $OUT_FILE (mode 600)"
  echo
  echo "Next steps:"
  echo "  1. Review $OUT_FILE"
  echo "  2. Copy values into your secrets backend (Vault / AWS SM / k8s Secret)"
  echo "  3. Delete $OUT_FILE — it is git-ignored but the file lives on disk"
fi
